replicas: 1

port: 3000

image:
  name: chat
  tag: backend

envFrom:
  configMaps:
    chat-backend : {}
  secrets:
    chat-backend : {}

resources:
  cpu: 0.25
  memory: 64Mi

configmap:
  data:
    test: test