apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana-config
  labels:
    component: kibana
data:
  kibana.yml: |
    server.name: kibana
    server.host: "0.0.0.0"

    elasticsearch.hosts: ["http://elasticsearch:9200"]
    elasticsearch.username: "kibana_system"
    elasticsearch.password: "dV_EHIn_H6wcWF_16KgK"

    xpack.encryptedSavedObjects.encryptionKey: "a5e85bfc397a4a5fbb29553f3b1c4bd7"
    telemetry.enabled: false
    monitoring.ui.container.elasticsearch.enabled: true
